services:
  db:
    image: postgres:16.1-alpine
    container_name: db
    hostname: db
    networks:
      - app_network
    env_file:
      - ./packages/database/.env
    environment:
      - TZ=Asia/Tokyo
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb.d/migration.sql:/docker-entrypoint-initdb.d/migration.sql

networks:
  app_network:
    driver: bridge

volumes:
  db-data:
