services:
  client:
    container_name: client
    build:
      context: ./apps/client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
      target: ${NODE_ENV:-production}
    env_file:
      - ./apps/client/.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - 80:80
    networks:
      - app_network
  server:
    container_name: server
    build:
      context: ./apps/server
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
      target: ${NODE_ENV:-production}
    env_file:
      - ./apps/server/.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  app_network:
    driver: bridge
    name: turbo-sample-app-network
