services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
      target: ${NODE_ENV:-development}
    env_file:
      - ./apps/client/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    networks:
      - app_network
    volumes:
      - ./apps/client:/app/apps/client
      - client-data:/app/apps/client/node_modules
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
      target: ${NODE_ENV:-development}
    env_file:
      - ./apps/server/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - app_network
    volumes:
      - ./apps/server:/app/apps/server
      - server-data:/app/apps/server/node_modules

networks:
  app_network:
    driver: bridge
    external: true
    name: turbo-sample-app-network

volumes:
  client-data:
  server-data: