services:
  db:
    image: postgres:16.1-alpine
    container_name: db
    hostname: db
    networks:
      - app_network
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Tokyo
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge
    external: true
    name: turbo-sample-app-network

volumes:
  db-data:
